language: go
go:
- '1.10'
sudo: false
before_script:
- pip install --user codecov
- 'mkdir -p $GOPATH/bin && wget -q https://github.com/barnybug/cli53/releases/download/0.6.0/upx -O $GOPATH/bin/upx && chmod +x $GOPATH/bin/upx'
script:
- make deps test-coverage
- codecov
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | VERSION=v0.34.2 bash
  on:
    tags: true
env:
  global:
    - secure: "M6bUhLlefRqTAfbVfQd2/j4/4CsifJqKQ6Szz2G5RTI0ADrbdNnS0m3SqTdk\nsbp/4cgwaQM+sgnISW2alDaGP+1PmkyXGyftZdLHM1NuGca8/yKVWy/vLW3e\nv++AiYPFLTRxoiZJ9j0bdHjGOffCMvotZhtc9xv0VXVijGdHiIM="
    - secure: "lnku5GaQtu8MLapFboAAsUzm2kYm+lVoshaJPmtod0gERoxiwaOUMMkY9Muq\nrezBxXy7dvHdDEEMoU0zelpJYfpxV6ql1vPjxgusVA6KouTTl1rTV3GfP0z7\nqUylHf1RqwYWNL0DkBURG44npnfkTT+F97qcq0kCCUAlLjAoyJg="
