name: Release
on:
  push:
    tags: '*.*.*'
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13.3
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.3

    - name: Check out code
      uses: actions/checkout@v1

    - name: Download Go dependencies
      run: go mod download

    - name: Get upx
      run: sudo apt install -y upx

    - name: Make release
      run: curl -sL https://git.io/goreleaser | VERSION=v0.34.2 bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
